# Generated by Django 3.0.4 on 2020-04-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCleaningRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.IntegerField(blank=True, null=True)),
                ('is_cleaning', models.IntegerField(blank=True, null=True)),
                ('cleaning_rule', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('create_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('is_custom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_cleaning_rule',
            },
        ),
        migrations.AddField(
            model_name='tattributemaplog',
            name='repo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tcleaninglog',
            name='repo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentityextractionlog',
            name='repo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tnormalizedlog',
            name='create_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tnormalizedlog',
            name='repo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
