# Generated by Django 3.0.5 on 2020-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200429_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNormalizedRuleDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('normalized_rule_id', models.IntegerField(blank=True, null=True)),
                ('attribute_id', models.IntegerField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('create_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_normalized_rule_detail',
            },
        ),
        migrations.RenameField(
            model_name='tnormalizedrule',
            old_name='attribute_id',
            new_name='rule_number',
        ),
        migrations.RemoveField(
            model_name='tnormalizedrule',
            name='create_id',
        ),
        migrations.RemoveField(
            model_name='tnormalizedrule',
            name='normalized_rule',
        ),
        migrations.RemoveField(
            model_name='tnormalizedrule',
            name='rule_state',
        ),
        migrations.AddField(
            model_name='tnormalizedrule',
            name='overall_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
