# Generated by Django 3.0.5 on 2020-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_tnormalizedrule_repo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattributemaplog',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
