# Generated by Django 3.0.5 on 2020-05-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200515_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmappingrule',
            name='coverage_rate',
        ),
        migrations.AddField(
            model_name='tmappingrule',
            name='coverage_rage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
