# Generated by Django 3.0.5 on 2020-05-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20200519_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmappingrule',
            old_name='coverage_rage',
            new_name='coverage_rate',
        ),
    ]
