# Generated by Django 3.0.5 on 2020-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20200519_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattribute',
            name='attribute_datatype',
        ),
        migrations.RemoveField(
            model_name='tdatatype',
            name='datatype_identifier',
        ),
        migrations.AddField(
            model_name='tattribute',
            name='data_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdatatype',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdatatype',
            name='repo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tdatatype',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
