# Generated by Django 3.0.5 on 2020-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20200608_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEventRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_subject_id', models.IntegerField(blank=True, null=True)),
                ('event_object_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('repo_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_event_rule',
            },
        ),
        migrations.CreateModel(
            name='TTriggerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_word', models.CharField(blank=True, max_length=20, null=True)),
                ('event_rule_id', models.IntegerField(blank=True, null=True)),
                ('repo_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_trigger_word',
            },
        ),
    ]
