# Generated by Django 3.0.5 on 2020-06-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_teventrule_ttriggerword'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcategory',
            name='category_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
